//SPADE_3,BLOCK_3,SEMI_3,SMG_3,SHOTGUN_3,GRENADE_3,SPADE,BLOCK,SEMI,SMG,SHOTGUN,GRENADE,
//PLAYERHEAD_B,PLAYERTORSO_B,PLAYERTORSOC_B,PLAYERARMS_B,PLAYERLEG_B,PLAYERLEGC_B,PLAYERDEAD_B,
//PLAYERHEAD_G,PLAYERTORSO_G,PLAYERTORSOC_G,PLAYERARMS_G,PLAYERLEG_G,PLAYERLEGC_G,PLAYERDEAD_G,
//INTEL_B,INTEL_G,CP_B,CP_G,CP_N,SEMITRACER,SMGTRACER,SHOTGUNTRACER,SEMICASING,SMGCASING,SHOTGUNCASING,"

enum KV6TYPE {
	SPADE_3 = 0,
	BLOCK_3 = 4,
	SEMI_3 = 8,
	SMG_3 = 12,
	SHOTGUN_3 = 16,
	GRENADE_3 = 20,

	SPADE = 24,
	BLOCK = 28,
	SEMI = 32,
	SMG = 36,
	SHOTGUN = 50,
	GRENADE = 54,

	PLAYERHEAD_B = 58,
	PLAYERTORSO_B = 62,
	PLAYERTORSOC_B = 66,
	PLAYERARMS_B = 70,
	PLAYERLEG_B = 74,
	PLAYERLEGC_B = 78,
	PLAYERDEAD_B = 82,

	PLAYERHEAD_G = 86,
	PLAYERTORSO_G = 90,
	PLAYERTORSOC_G = 94,
	PLAYERARMS_G = 98,
	PLAYERLEG_G = 102,
	PLAYERLEGC_G = 106,
	PLAYERDEAD_G = 110,

	INTEL_B = 114,
	INTEL_G = 118,
	CP_B = 122,
	CP_G = 126,
	CP_N = 130,
	SEMITRACER = 134,
	SMGTRACER = 138,
	SHOTGUNTRACER = 142,
	SEMICASING = 146,
	SMGCASING = 150,
	SHOTGUNCASING = 154
};